name: Build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

# TODO: maybe add testing here too.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build

      - name: Build package
        run: python -m build

      - name: Upload whl artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-seatsurfing-whl
          path: |
            dist/**/*.whl
