name: Build and Publish

on: push

# TODO: maybe add testing here too before the build.

jobs:
  build:
    if: github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build

      - name: Build package
        run: python -m build

      - name: Upload whl artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-seatsurfing-whl
          path: |
            dist/**/*.whl

      - name: Upload tar artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-seatsurfing-tar
          path: |
            dist/**/*.tar.gz

  publish-testpypi:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-seatsurfing-whl
          path: python-seatsurfing-whl/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: python-seatsurfing-whl/

  publish-pypi:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build, release]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-seatsurfing-whl
          path: python-seatsurfing-whl/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: python-seatsurfing-whl/

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-seatsurfing-tar
          path: python-seatsurfing-tar/

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} ./python-seatsurfing-tar/* \
            --generate-notes \
            --title "Release ${GITHUB_REF#refs/tags/}"
