name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-seatsurfing-whl
          path: python-seatsurfing-whl/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
